### ISSUE TITLE
Multipage PDF creates strange footer and header

### ISSUE THREAD

**Issue by cloudscape-germany** [roginfarrer/webpage-pdf-resume#2]
When I have multipage PDF, and I can not reduce it anymore as you wrote in README.md this is not an option for me, then I get this fugly, unutilised rounded fields at the tops and bottoms of the pages. Can you help ?

<img width="319" alt="Top bottom pdf resume multipage" src="https://github.com/user-attachments/assets/bb56b368-0672-4d32-8172-522cc23c155e">

**Comment by roginfarrer** [comment]
That looks like it could be the Astro devbar? If you disable it, does that go away?
